mesosMaster: zk://registry.dmitriyvolk.net:2181/mesos
imageName: registry.dmitriyvolk.net:5000/sqrt/sqrt-client
---
spring:
    profiles: prod
eureka:
    client:
        serviceUrl:
            defaultZone: http://registry.dmitriyvolk.net:8761/eureka/
